// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SAPLSServer.Models;

#nullable disable

namespace SAPLSServer.Migrations
{
    [DbContext(typeof(SaplsContext))]
    [Migration("20250813104109_LatestBase")]
    partial class LatestBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SAPLSServer.Models.AdminProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("AdminId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId")
                        .HasName("PK__AdminPro__1788CC4CE4751A99");

                    b.HasIndex(new[] { "AdminId" }, "IX_AdminProfile_AdminId");

                    b.HasIndex(new[] { "Role" }, "IX_AdminProfile_Role");

                    b.HasIndex(new[] { "UserId" }, "UQ__AdminPro__1788CC4DD8C91BA2")
                        .IsUnique();

                    b.HasIndex(new[] { "AdminId" }, "UQ__AdminPro__719FE4893278F34A")
                        .IsUnique();

                    b.ToTable("AdminProfile", (string)null);
                });

            modelBuilder.Entity("SAPLSServer.Models.AttachedFile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CdnUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CloudUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StorageFileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UploadAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Attached__3214EC07E4AB6E4D");

                    b.HasIndex(new[] { "OriginalFileName" }, "IX_AttachedFile_Name");

                    b.HasIndex(new[] { "UploadAt" }, "IX_AttachedFile_UploadAt");

                    b.HasIndex(new[] { "Id" }, "UQ__Attached__3214EC069CF63EC4")
                        .IsUnique();

                    b.ToTable("AttachedFile", (string)null);
                });

            modelBuilder.Entity("SAPLSServer.Models.ClientProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("BackCitizenIdCardImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CitizenId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("DeviceToken")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FrontCitizenIdCardImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PlaceOfOrigin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PlaceOfResidence")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Sex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ShareCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId")
                        .HasName("PK__ClientPr__1788CC4C088F8864");

                    b.HasIndex(new[] { "CitizenId" }, "IX_ClientProfile_CitizenId");

                    b.HasIndex(new[] { "ShareCode" }, "IX_ClientProfile_ShareCode");

                    b.HasIndex(new[] { "UserId" }, "UQ__ClientPr__1788CC4D922DF55A")
                        .IsUnique();

                    b.HasIndex(new[] { "ShareCode" }, "UQ__ClientPr__208770411C2E5E47")
                        .IsUnique();

                    b.HasIndex(new[] { "CitizenId" }, "UQ__ClientPr__6E49FA0D3E44AD25")
                        .IsUnique();

                    b.ToTable("ClientProfile", (string)null);
                });

            modelBuilder.Entity("SAPLSServer.Models.GuestParkingSession", b =>
                {
                    b.Property<string>("CheckInStaffId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime?>("CheckOutDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CheckOutStaffId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("EntryBackCaptureUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EntryDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntryFrontCaptureUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExitBackCaptureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ExitDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExitFrontCaptureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ParkingLotId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasIndex("CheckInStaffId");

                    b.HasIndex("CheckOutStaffId");

                    b.HasIndex("ParkingLotId");

                    b.ToTable("GuestParkingSession", (string)null);
                });

            modelBuilder.Entity("SAPLSServer.Models.IncidenceEvidence", b =>
                {
                    b.Property<string>("AttachedFileId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("IncidenceReportId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("AttachedFileId")
                        .HasName("PK__Incidenc__3214EC07194AA9EF");

                    b.HasIndex("IncidenceReportId");

                    b.HasIndex(new[] { "AttachedFileId" }, "UQ__Incidenc__3214EC06222FE1FC")
                        .IsUnique();

                    b.ToTable("IncidenceEvidence", (string)null);
                });

            modelBuilder.Entity("SAPLSServer.Models.IncidenceReport", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ParkingLotId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Medium");

                    b.Property<DateTime>("ReportedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ReporterId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Open");

                    b.HasKey("Id")
                        .HasName("PK__Incidenc__3214EC07D412DE08");

                    b.HasIndex("ParkingLotId");

                    b.HasIndex(new[] { "Priority" }, "IX_IncidenceReport_Priority");

                    b.HasIndex(new[] { "ReportedDate" }, "IX_IncidenceReport_ReportedDate");

                    b.HasIndex(new[] { "ReporterId" }, "IX_IncidenceReport_ReporterId");

                    b.HasIndex(new[] { "Status" }, "IX_IncidenceReport_Status");

                    b.HasIndex(new[] { "Id" }, "UQ__Incidenc__3214EC06DE213DDD")
                        .IsUnique();

                    b.ToTable("IncidenceReport", (string)null);
                });

            modelBuilder.Entity("SAPLSServer.Models.ParkingFeeSchedule", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<decimal>("AdditionalFee")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<int>("AdditionalMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(60);

                    b.Property<string>("DayOfWeeks")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<int>("EndTime")
                        .HasColumnType("int");

                    b.Property<string>("ForVehicleType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Car");

                    b.Property<decimal>("InitialFee")
                        .HasColumnType("decimal(8, 2)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ParkingLotId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("StartTime")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__ParkingF__3214EC074B624F3F");

                    b.HasIndex(new[] { "ForVehicleType" }, "IX_ParkingFeeSchedule_ForVehicleType");

                    b.HasIndex(new[] { "IsActive" }, "IX_ParkingFeeSchedule_IsActive");

                    b.HasIndex(new[] { "ParkingLotId" }, "IX_ParkingFeeSchedule_ParkingLotId");

                    b.HasIndex(new[] { "Id" }, "UQ__ParkingF__3214EC0675353B44")
                        .IsUnique();

                    b.ToTable("ParkingFeeSchedule", (string)null);
                });

            modelBuilder.Entity("SAPLSServer.Models.ParkingLot", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CheckSumKey")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ClientKey")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ParkingLotOwnerId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("TotalParkingSlot")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__ParkingL__3214EC07D98A3F04");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex(new[] { "CreatedAt" }, "IX_ParkingLot_CreatedAt");

                    b.HasIndex(new[] { "ParkingLotOwnerId" }, "IX_ParkingLot_ParkingLotOwnerId");

                    b.HasIndex(new[] { "Status" }, "IX_ParkingLot_Status");

                    b.HasIndex(new[] { "Id" }, "UQ__ParkingL__3214EC066134085F")
                        .IsUnique();

                    b.ToTable("ParkingLot", (string)null);
                });

            modelBuilder.Entity("SAPLSServer.Models.ParkingLotOwnerProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ParkingLotOwnerId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId")
                        .HasName("PK__ParkingL__1788CC4C6E170A53");

                    b.HasIndex(new[] { "ParkingLotOwnerId" }, "IX_ParkingLotOwnerProfile_ParkingLotOwnerId");

                    b.HasIndex(new[] { "UserId" }, "UQ__ParkingL__1788CC4D0B965F24")
                        .IsUnique();

                    b.HasIndex(new[] { "ParkingLotOwnerId" }, "UQ__ParkingL__F2333F3FF0F8151B")
                        .IsUnique();

                    b.ToTable("ParkingLotOwnerProfile", (string)null);
                });

            modelBuilder.Entity("SAPLSServer.Models.ParkingLotShift", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DayOfWeeks")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("EndTime")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParkingLotId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StartTime")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParkingLotId");

                    b.ToTable("ParkingLotShift", (string)null);
                });

            modelBuilder.Entity("SAPLSServer.Models.ParkingSession", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CheckInStaffId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime?>("CheckOutDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("CheckOutStaffId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasDefaultValue("");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("DriverId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("EntryBackCaptureUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EntryDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("EntryFrontCaptureUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExitBackCaptureUrl")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<DateTime?>("ExitDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("ExitFrontCaptureUrl")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("ParkingLotId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Cash");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Id")
                        .HasName("PK__ParkingS__3214EC076244C9DD");

                    b.HasIndex("CheckInStaffId");

                    b.HasIndex("CheckOutStaffId");

                    b.HasIndex(new[] { "ClientId" }, "IX_ParkingSession_ClientId");

                    b.HasIndex(new[] { "EntryDateTime" }, "IX_ParkingSession_EntryDateTime");

                    b.HasIndex(new[] { "ExitDateTime" }, "IX_ParkingSession_ExitDateTime");

                    b.HasIndex(new[] { "ParkingLotId" }, "IX_ParkingSession_ParkingLotId");

                    b.HasIndex(new[] { "PaymentMethod" }, "IX_ParkingSession_PaymentMethod");

                    b.HasIndex(new[] { "VehicleId" }, "IX_ParkingSession_VehicleId");

                    b.HasIndex(new[] { "Id" }, "UQ__ParkingS__3214EC06ED8B4805")
                        .IsUnique();

                    b.HasIndex(new[] { "TransactionId" }, "UQ__ParkingS__55433A6AF76245F4")
                        .IsUnique()
                        .HasFilter("[TransactionId] IS NOT NULL");

                    b.ToTable("ParkingSession", (string)null);
                });

            modelBuilder.Entity("SAPLSServer.Models.PaymentSource", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ParkingLotOwnerId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id")
                        .HasName("PK__PaymentS__3214EC074DD2D6E5");

                    b.HasIndex(new[] { "ParkingLotOwnerId" }, "IX_PaymentSource_ParkingLotOwnerId");

                    b.HasIndex(new[] { "Id" }, "UQ__PaymentS__3214EC064155607D")
                        .IsUnique();

                    b.ToTable("PaymentSource", (string)null);
                });

            modelBuilder.Entity("SAPLSServer.Models.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParkingLotOwnerUserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("ParkingLotOwnerUserId");

                    b.ToTable("Receipt", (string)null);
                });

            modelBuilder.Entity("SAPLSServer.Models.Request", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("InternalNote")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("LastUpdatePersonId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ResponseMessage")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("SenderId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Open");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Request__3214EC07B2ACCA82");

                    b.HasIndex(new[] { "LastUpdatePersonId" }, "IX_Request_LastUpdatePersonId");

                    b.HasIndex(new[] { "SenderId" }, "IX_Request_SenderId");

                    b.HasIndex(new[] { "Status" }, "IX_Request_Status");

                    b.HasIndex(new[] { "SubmittedAt" }, "IX_Request_SubmittedAt");

                    b.HasIndex(new[] { "Id" }, "UQ__Request__3214EC06DDE85BED")
                        .IsUnique();

                    b.ToTable("Request", (string)null);
                });

            modelBuilder.Entity("SAPLSServer.Models.RequestAttachedFile", b =>
                {
                    b.Property<string>("AttachedFileId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("AttachedFileId")
                        .HasName("PK__RequestA__3214EC07B9EE57B9");

                    b.HasIndex("RequestId");

                    b.HasIndex(new[] { "AttachedFileId" }, "UQ__RequestA__3214EC06152DDA3B")
                        .IsUnique();

                    b.ToTable("RequestAttachedFile", (string)null);
                });

            modelBuilder.Entity("SAPLSServer.Models.SharedVehicle", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime?>("AcceptAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AccessDuration")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpireAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InviteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SharedPersonId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Id")
                        .HasName("PK__SharedVe__3214EC07EDA49C12");

                    b.HasIndex(new[] { "AcceptAt" }, "IX_SharedVehicle_AcceptAt");

                    b.HasIndex(new[] { "ExpireAt" }, "IX_SharedVehicle_ExpireAt");

                    b.HasIndex(new[] { "InviteAt" }, "IX_SharedVehicle_InviteAt");

                    b.HasIndex(new[] { "SharedPersonId" }, "IX_SharedVehicle_SharedPersonId");

                    b.HasIndex(new[] { "VehicleId" }, "IX_SharedVehicle_VehicleId");

                    b.HasIndex(new[] { "Id" }, "UQ__SharedVe__3214EC065D8B45A9")
                        .IsUnique();

                    b.ToTable("SharedVehicle", (string)null);
                });

            modelBuilder.Entity("SAPLSServer.Models.ShiftDiary", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ParkingLotId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("SenderId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Id")
                        .HasName("PK__ShiftDia__3214EC0708509E2F");

                    b.HasIndex(new[] { "CreatedAt" }, "IX_ShiftDiary_CreatedAt");

                    b.HasIndex(new[] { "ParkingLotId" }, "IX_ShiftDiary_ParkingLotId");

                    b.HasIndex(new[] { "SenderId" }, "IX_ShiftDiary_SenderId");

                    b.HasIndex(new[] { "Id" }, "UQ__ShiftDia__3214EC06C45A8081")
                        .IsUnique();

                    b.ToTable("ShiftDiary", (string)null);
                });

            modelBuilder.Entity("SAPLSServer.Models.StaffProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ParkingLotId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId")
                        .HasName("PK__StaffPro__1788CC4CACF4A0F8");

                    b.HasIndex(new[] { "ParkingLotId" }, "IX_StaffProfile_ParkingLotId");

                    b.HasIndex(new[] { "StaffId" }, "IX_StaffProfile_StaffId");

                    b.HasIndex(new[] { "UserId" }, "UQ__StaffPro__1788CC4D3B12EFC1")
                        .IsUnique();

                    b.HasIndex(new[] { "StaffId" }, "UQ__StaffPro__96D4AB161AE0F057")
                        .IsUnique();

                    b.ToTable("StaffProfile", (string)null);
                });

            modelBuilder.Entity("SAPLSServer.Models.Subscription", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdateById")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdateById");

                    b.ToTable("Subscription", (string)null);
                });

            modelBuilder.Entity("SAPLSServer.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OneTimePassword")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfileImageUrl")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Inactive");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__User__3214EC0786524D8F");

                    b.HasIndex(new[] { "CreatedAt" }, "IX_User_CreatedAt");

                    b.HasIndex(new[] { "Email" }, "IX_User_Email");

                    b.HasIndex(new[] { "Status" }, "IX_User_Status");

                    b.HasIndex(new[] { "Id" }, "UQ__User__3214EC06366C8D89")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "UQ__User__5C7E359E4EC59181")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__User__A9D1053456547DAC")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("SAPLSServer.Models.Vehicle", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("BackVehicleRegistrationCertificateUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChassisNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CurrentHolderId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("EngineNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FrontVehicleRegistrationCertificateUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("OwnerVehicleFullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SharingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Unavailable");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Inactive");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Vehicle__3214EC073BBDFC5B");

                    b.HasIndex("CurrentHolderId");

                    b.HasIndex(new[] { "CreatedAt" }, "IX_Vehicle_CreatedAt");

                    b.HasIndex(new[] { "LicensePlate" }, "IX_Vehicle_LicensePlate");

                    b.HasIndex(new[] { "OwnerId" }, "IX_Vehicle_OwnerId");

                    b.HasIndex(new[] { "SharingStatus" }, "IX_Vehicle_SharingStatus");

                    b.HasIndex(new[] { "Status" }, "IX_Vehicle_Status");

                    b.HasIndex(new[] { "LicensePlate" }, "UQ__Vehicle__026BC15CAE30AED6")
                        .IsUnique();

                    b.HasIndex(new[] { "Id" }, "UQ__Vehicle__3214EC0678F92770")
                        .IsUnique();

                    b.ToTable("Vehicle", (string)null);
                });

            modelBuilder.Entity("SAPLSServer.Models.WhiteList", b =>
                {
                    b.Property<string>("ParkingLotId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ClientId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<DateTime?>("ExpireAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("ParkingLotId", "ClientId");

                    b.HasIndex(new[] { "AddedAt" }, "IX_WhiteList_AddedDate");

                    b.HasIndex(new[] { "ClientId" }, "IX_WhiteList_ClientId");

                    b.HasIndex(new[] { "ExpireAt" }, "IX_WhiteList_ExpiredDate");

                    b.HasIndex(new[] { "ParkingLotId", "ClientId" }, "UQ_WhiteList_ParkingLot_Client")
                        .IsUnique();

                    b.ToTable("WhiteList", (string)null);
                });

            modelBuilder.Entity("StaffShift", b =>
                {
                    b.Property<string>("StaffUserId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("ParkingLotShiftId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("StaffUserId", "ParkingLotShiftId");

                    b.HasIndex("ParkingLotShiftId");

                    b.ToTable("StaffShift", (string)null);
                });

            modelBuilder.Entity("SAPLSServer.Models.AdminProfile", b =>
                {
                    b.HasOne("SAPLSServer.Models.User", "User")
                        .WithOne("AdminProfile")
                        .HasForeignKey("SAPLSServer.Models.AdminProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("AdminProfile_fk0");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SAPLSServer.Models.ClientProfile", b =>
                {
                    b.HasOne("SAPLSServer.Models.User", "User")
                        .WithOne("ClientProfile")
                        .HasForeignKey("SAPLSServer.Models.ClientProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ClientProfile_fk0");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SAPLSServer.Models.GuestParkingSession", b =>
                {
                    b.HasOne("SAPLSServer.Models.StaffProfile", "CheckInStaff")
                        .WithMany()
                        .HasForeignKey("CheckInStaffId")
                        .HasConstraintName("FK_GuestParkingSession_CheckInStaff");

                    b.HasOne("SAPLSServer.Models.StaffProfile", "CheckOutStaff")
                        .WithMany()
                        .HasForeignKey("CheckOutStaffId")
                        .HasConstraintName("FK_GuestParkingSession_CheckOutStaff");

                    b.HasOne("SAPLSServer.Models.ParkingLot", "ParkingLot")
                        .WithMany()
                        .HasForeignKey("ParkingLotId")
                        .IsRequired()
                        .HasConstraintName("FK_GuestParkingSession_ParkingLot");

                    b.Navigation("CheckInStaff");

                    b.Navigation("CheckOutStaff");

                    b.Navigation("ParkingLot");
                });

            modelBuilder.Entity("SAPLSServer.Models.IncidenceEvidence", b =>
                {
                    b.HasOne("SAPLSServer.Models.AttachedFile", "AttachedFile")
                        .WithOne("IncidenceEvidence")
                        .HasForeignKey("SAPLSServer.Models.IncidenceEvidence", "AttachedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("IncidenceEvidence_fk0");

                    b.HasOne("SAPLSServer.Models.IncidenceReport", "IncidenceReport")
                        .WithMany("IncidenceEvidences")
                        .HasForeignKey("IncidenceReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("IncidenceEvidence_fk1");

                    b.Navigation("AttachedFile");

                    b.Navigation("IncidenceReport");
                });

            modelBuilder.Entity("SAPLSServer.Models.IncidenceReport", b =>
                {
                    b.HasOne("SAPLSServer.Models.ParkingLot", "ParkingLot")
                        .WithMany("IncidenceReports")
                        .HasForeignKey("ParkingLotId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_IncidenceReport_ParkingLot");

                    b.HasOne("SAPLSServer.Models.StaffProfile", "Reporter")
                        .WithMany("IncidenceReports")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("IncidenceReport_fk6");

                    b.Navigation("ParkingLot");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("SAPLSServer.Models.ParkingFeeSchedule", b =>
                {
                    b.HasOne("SAPLSServer.Models.ParkingLot", "ParkingLot")
                        .WithMany("ParkingFeeSchedules")
                        .HasForeignKey("ParkingLotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ParkingFeeSchedule_fk10");

                    b.Navigation("ParkingLot");
                });

            modelBuilder.Entity("SAPLSServer.Models.ParkingLot", b =>
                {
                    b.HasOne("SAPLSServer.Models.ParkingLotOwnerProfile", "ParkingLotOwner")
                        .WithMany("ParkingLots")
                        .HasForeignKey("ParkingLotOwnerId")
                        .IsRequired()
                        .HasConstraintName("ParkingLot_fk8");

                    b.HasOne("SAPLSServer.Models.Subscription", "Subscription")
                        .WithMany("ParkingLots")
                        .HasForeignKey("SubscriptionId")
                        .IsRequired()
                        .HasConstraintName("FK_ParkingLot_Subscription_fk3");

                    b.Navigation("ParkingLotOwner");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("SAPLSServer.Models.ParkingLotOwnerProfile", b =>
                {
                    b.HasOne("SAPLSServer.Models.User", "User")
                        .WithOne("ParkingLotOwnerProfile")
                        .HasForeignKey("SAPLSServer.Models.ParkingLotOwnerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ParkingLotOwnerProfile_fk0");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SAPLSServer.Models.ParkingLotShift", b =>
                {
                    b.HasOne("SAPLSServer.Models.ParkingLot", "ParkingLot")
                        .WithMany("ParkingLotShifts")
                        .HasForeignKey("ParkingLotId")
                        .IsRequired()
                        .HasConstraintName("FK_ParkingLotShift_ParkingLot_fk1");

                    b.Navigation("ParkingLot");
                });

            modelBuilder.Entity("SAPLSServer.Models.ParkingSession", b =>
                {
                    b.HasOne("SAPLSServer.Models.StaffProfile", "CheckInStaff")
                        .WithMany("ParkingSessionCheckInStaffs")
                        .HasForeignKey("CheckInStaffId")
                        .HasConstraintName("ParkingSession_fk3");

                    b.HasOne("SAPLSServer.Models.StaffProfile", "CheckOutStaff")
                        .WithMany("ParkingSessionCheckOutStaffs")
                        .HasForeignKey("CheckOutStaffId")
                        .HasConstraintName("ParkingSession_fk4");

                    b.HasOne("SAPLSServer.Models.ClientProfile", "Client")
                        .WithMany("ParkingSessions")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("ParkingSession_fk5");

                    b.HasOne("SAPLSServer.Models.ParkingLot", "ParkingLot")
                        .WithMany("ParkingSessions")
                        .HasForeignKey("ParkingLotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ParkingSession_fk2");

                    b.HasOne("SAPLSServer.Models.Vehicle", "Vehicle")
                        .WithMany("ParkingSessions")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ParkingSession_fk1");

                    b.Navigation("CheckInStaff");

                    b.Navigation("CheckOutStaff");

                    b.Navigation("Client");

                    b.Navigation("ParkingLot");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("SAPLSServer.Models.PaymentSource", b =>
                {
                    b.HasOne("SAPLSServer.Models.ParkingLotOwnerProfile", "ParkingLotOwner")
                        .WithMany("PaymentSources")
                        .HasForeignKey("ParkingLotOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("PaymentSource_fk5");

                    b.Navigation("ParkingLotOwner");
                });

            modelBuilder.Entity("SAPLSServer.Models.Receipt", b =>
                {
                    b.HasOne("SAPLSServer.Models.ParkingLotOwnerProfile", "ParkingLotOwnerUser")
                        .WithMany("Receipts")
                        .HasForeignKey("ParkingLotOwnerUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Receipt_ParkingLotOwner_fk1");

                    b.Navigation("ParkingLotOwnerUser");
                });

            modelBuilder.Entity("SAPLSServer.Models.Request", b =>
                {
                    b.HasOne("SAPLSServer.Models.AdminProfile", "LastUpdatePerson")
                        .WithMany("Requests")
                        .HasForeignKey("LastUpdatePersonId")
                        .HasConstraintName("Request_fk8");

                    b.HasOne("SAPLSServer.Models.User", "Sender")
                        .WithMany("Requests")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Request_fk_Sender");

                    b.Navigation("LastUpdatePerson");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("SAPLSServer.Models.RequestAttachedFile", b =>
                {
                    b.HasOne("SAPLSServer.Models.AttachedFile", "AttachedFile")
                        .WithOne("RequestAttachedFile")
                        .HasForeignKey("SAPLSServer.Models.RequestAttachedFile", "AttachedFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("RequestAttachedFile_fk0");

                    b.HasOne("SAPLSServer.Models.Request", "Request")
                        .WithMany("RequestAttachedFiles")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("RequestAttachedFile_fk1");

                    b.Navigation("AttachedFile");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("SAPLSServer.Models.SharedVehicle", b =>
                {
                    b.HasOne("SAPLSServer.Models.ClientProfile", "SharedPerson")
                        .WithMany("SharedVehicles")
                        .HasForeignKey("SharedPersonId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("SharedVehicle_fk7");

                    b.HasOne("SAPLSServer.Models.Vehicle", "Vehicle")
                        .WithMany("SharedVehicles")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("SharedVehicle_fk1");

                    b.Navigation("SharedPerson");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("SAPLSServer.Models.ShiftDiary", b =>
                {
                    b.HasOne("SAPLSServer.Models.ParkingLot", "ParkingLot")
                        .WithMany("ShiftDiaries")
                        .HasForeignKey("ParkingLotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ShiftDiary_fk4");

                    b.HasOne("SAPLSServer.Models.StaffProfile", "Sender")
                        .WithMany("ShiftDiaries")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("ShiftDiary_fk5");

                    b.Navigation("ParkingLot");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("SAPLSServer.Models.StaffProfile", b =>
                {
                    b.HasOne("SAPLSServer.Models.ParkingLot", "ParkingLot")
                        .WithMany("StaffProfiles")
                        .HasForeignKey("ParkingLotId")
                        .IsRequired()
                        .HasConstraintName("StaffProfile_fk2");

                    b.HasOne("SAPLSServer.Models.User", "User")
                        .WithOne("StaffProfile")
                        .HasForeignKey("SAPLSServer.Models.StaffProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("StaffProfile_fk0");

                    b.Navigation("ParkingLot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SAPLSServer.Models.Subscription", b =>
                {
                    b.HasOne("SAPLSServer.Models.AdminProfile", "CreateBy")
                        .WithMany("SubscriptionCreator")
                        .HasForeignKey("CreatedById")
                        .IsRequired()
                        .HasConstraintName("FK_Subscription_CreatedBy_fk1");

                    b.HasOne("SAPLSServer.Models.AdminProfile", "UpdateBy")
                        .WithMany("SubscriptionUpdater")
                        .HasForeignKey("UpdateById")
                        .IsRequired()
                        .HasConstraintName("FK_Subscription_UpdatedBy_fk1");

                    b.Navigation("CreateBy");

                    b.Navigation("UpdateBy");
                });

            modelBuilder.Entity("SAPLSServer.Models.Vehicle", b =>
                {
                    b.HasOne("SAPLSServer.Models.ClientProfile", "CurrentHolder")
                        .WithMany("VehicleCurrentHolders")
                        .HasForeignKey("CurrentHolderId")
                        .HasConstraintName("Vehicle_fk13");

                    b.HasOne("SAPLSServer.Models.ClientProfile", "Owner")
                        .WithMany("VehicleOwners")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("Vehicle_fk12");

                    b.Navigation("CurrentHolder");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SAPLSServer.Models.WhiteList", b =>
                {
                    b.HasOne("SAPLSServer.Models.ClientProfile", "Client")
                        .WithMany("WhiteLists")
                        .HasForeignKey("ClientId")
                        .IsRequired()
                        .HasConstraintName("FK_WhiteList_fk1");

                    b.HasOne("SAPLSServer.Models.ParkingLot", "ParkingLot")
                        .WithMany("WhiteLists")
                        .HasForeignKey("ParkingLotId")
                        .IsRequired()
                        .HasConstraintName("FK_WhiteList_fk0");

                    b.Navigation("Client");

                    b.Navigation("ParkingLot");
                });

            modelBuilder.Entity("StaffShift", b =>
                {
                    b.HasOne("SAPLSServer.Models.ParkingLotShift", null)
                        .WithMany()
                        .HasForeignKey("ParkingLotShiftId")
                        .IsRequired()
                        .HasConstraintName("FK_StaffShift_ParkingLotShiftId_fk2");

                    b.HasOne("SAPLSServer.Models.StaffProfile", null)
                        .WithMany()
                        .HasForeignKey("StaffUserId")
                        .IsRequired()
                        .HasConstraintName("FK_StaffShift_Staff_fk1");
                });

            modelBuilder.Entity("SAPLSServer.Models.AdminProfile", b =>
                {
                    b.Navigation("Requests");

                    b.Navigation("SubscriptionCreator");

                    b.Navigation("SubscriptionUpdater");
                });

            modelBuilder.Entity("SAPLSServer.Models.AttachedFile", b =>
                {
                    b.Navigation("IncidenceEvidence");

                    b.Navigation("RequestAttachedFile");
                });

            modelBuilder.Entity("SAPLSServer.Models.ClientProfile", b =>
                {
                    b.Navigation("ParkingSessions");

                    b.Navigation("SharedVehicles");

                    b.Navigation("VehicleCurrentHolders");

                    b.Navigation("VehicleOwners");

                    b.Navigation("WhiteLists");
                });

            modelBuilder.Entity("SAPLSServer.Models.IncidenceReport", b =>
                {
                    b.Navigation("IncidenceEvidences");
                });

            modelBuilder.Entity("SAPLSServer.Models.ParkingLot", b =>
                {
                    b.Navigation("IncidenceReports");

                    b.Navigation("ParkingFeeSchedules");

                    b.Navigation("ParkingLotShifts");

                    b.Navigation("ParkingSessions");

                    b.Navigation("ShiftDiaries");

                    b.Navigation("StaffProfiles");

                    b.Navigation("WhiteLists");
                });

            modelBuilder.Entity("SAPLSServer.Models.ParkingLotOwnerProfile", b =>
                {
                    b.Navigation("ParkingLots");

                    b.Navigation("PaymentSources");

                    b.Navigation("Receipts");
                });

            modelBuilder.Entity("SAPLSServer.Models.Request", b =>
                {
                    b.Navigation("RequestAttachedFiles");
                });

            modelBuilder.Entity("SAPLSServer.Models.StaffProfile", b =>
                {
                    b.Navigation("IncidenceReports");

                    b.Navigation("ParkingSessionCheckInStaffs");

                    b.Navigation("ParkingSessionCheckOutStaffs");

                    b.Navigation("ShiftDiaries");
                });

            modelBuilder.Entity("SAPLSServer.Models.Subscription", b =>
                {
                    b.Navigation("ParkingLots");
                });

            modelBuilder.Entity("SAPLSServer.Models.User", b =>
                {
                    b.Navigation("AdminProfile");

                    b.Navigation("ClientProfile");

                    b.Navigation("ParkingLotOwnerProfile");

                    b.Navigation("Requests");

                    b.Navigation("StaffProfile");
                });

            modelBuilder.Entity("SAPLSServer.Models.Vehicle", b =>
                {
                    b.Navigation("ParkingSessions");

                    b.Navigation("SharedVehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
