namespace SAPLSServer.Constants
{
    /// <summary>
    /// Provides strongly-typed keys for error and success messages in UPPER_SNAKE_CASE.
    /// </summary>
    public static class MessageKeys
    {
        public const string EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS";
        public const string CITIZEN_ID_ALREADY_EXISTS = "CITIZEN_ID_ALREADY_EXISTS";
        public const string ADMIN_ID_ALREADY_EXISTS = "ADMIN_ID_ALREADY_EXISTS";
        public const string STAFF_ID_ALREADY_EXISTS = "STAFF_ID_ALREADY_EXISTS";
        public const string PARKING_LOT_OWNER_ID_ALREADY_EXISTS = "PARKING_LOT_OWNER_ID_ALREADY_EXISTS";
        public const string USER_NOT_FOUND = "USER_NOT_FOUND";
        public const string INVALID_OLD_PASSWORD = "INVALID_OLD_PASSWORD";
        public const string ADMIN_PROFILE_NOT_FOUND = "ADMIN_PROFILE_NOT_FOUND";
        public const string CLIENT_PROFILE_NOT_FOUND = "CLIENT_PROFILE_NOT_FOUND";
        public const string STAFF_PROFILE_NOT_FOUND = "STAFF_PROFILE_NOT_FOUND";
        public const string PARKING_LOT_OWNER_PROFILE_NOT_FOUND = "PARKING_LOT_OWNER_PROFILE_NOT_FOUND";
        public const string INVALID_USER_STATUS = "INVALID_USER_STATUS";
        public const string INVALID_CREDENTIALS_OR_USER_NOT_ACTIVE = "INVALID_CREDENTIALS_OR_USER_NOT_ACTIVE";
        public const string INVALID_CREDENTIALS_OR_CLIENT_NOT_ACTIVE = "INVALID_CREDENTIALS_OR_CLIENT_NOT_ACTIVE";
        public const string PASSWORD_UPDATED_SUCCESSFULLY = "PASSWORD_UPDATED_SUCCESSFULLY";
        public const string PROFILE_IMAGE_UPDATED_SUCCESSFULLY = "PROFILE_IMAGE_UPDATED_SUCCESSFULLY";
        public const string USER_UPDATED_SUCCESSFULLY = "USER_UPDATED_SUCCESSFULLY";
        public const string ADMIN_PROFILE_CREATED_SUCCESSFULLY = "ADMIN_PROFILE_CREATED_SUCCESSFULLY";
        public const string ADMIN_PROFILE_UPDATED_SUCCESSFULLY = "ADMIN_PROFILE_UPDATED_SUCCESSFULLY";
        public const string CLIENT_PROFILE_CREATED_SUCCESSFULLY = "CLIENT_PROFILE_CREATED_SUCCESSFULLY";
        public const string CLIENT_PROFILE_UPDATED_SUCCESSFULLY = "CLIENT_PROFILE_UPDATED_SUCCESSFULLY";
        public const string PARKING_LOT_OWNER_PROFILE_CREATED_SUCCESSFULLY = "PARKING_LOT_OWNER_PROFILE_CREATED_SUCCESSFULLY";
        public const string PARKING_LOT_OWNER_PROFILE_UPDATED_SUCCESSFULLY = "PARKING_LOT_OWNER_PROFILE_UPDATED_SUCCESSFULLY";
        public const string STAFF_PROFILE_CREATED_SUCCESSFULLY = "STAFF_PROFILE_CREATED_SUCCESSFULLY";
        public const string STAFF_PROFILE_UPDATED_SUCCESSFULLY = "STAFF_PROFILE_UPDATED_SUCCESSFULLY";
        public const string GET_ADMIN_PROFILE_DETAILS_SUCCESSFULLY = "GET_ADMIN_PROFILE_DETAILS_SUCCESSFULLY";
        public const string GET_ADMIN_PROFILES_PAGE_SUCCESSFULLY = "GET_CLIENT_PROFILE_DETAILS_SUCCESSFULLY";
        public const string GET_CLIENT_PROFILE_DETAILS_SUCCESSFULLY = "GET_CLIENT_PROFILE_DETAILS_SUCCESSFULLY";
        public const string GET_CLIENT_PROFILES_PAGE_SUCCESSFULLY = "GET_CLIENT_PROFILES_PAGE_SUCCESSFULLY";
        public const string GET_PARKING_LOT_OWNER_PROFILE_DETAILS_SUCCESSFULLY = "GET_PARKING_LOT_OWNER_PROFILE_DETAILS_SUCCESSFULLY";
        public const string GET_PARKING_LOT_OWNER_PROFILES_PAGE_SUCCESSFULLY = "GET_PARKING_LOT_OWNER_PROFILES_PAGE_SUCCESSFULLY";
        public const string GET_STAFF_PROFILE_DETAILS_SUCCESSFULLY = "GET_STAFF_PROFILE_DETAILS_SUCCESSFULLY";
        public const string GET_STAFF_PROFILES_PAGE_SUCCESSFULLY = "GET_STAFF_PROFILES_PAGE_SUCCESSFULLY";
        public const string CLIENT_AUTHENTICATED_SUCCESSFULLY = "CLIENT_AUTHENTICATED_SUCCESSFULLY";
        public const string USER_AUTHENTICATED_SUCCESSFULLY = "USER_AUTHENTICATED_SUCCESSFULLY";
        public const string PHONE_ALREADY_EXISTS = "PHONE_ALREADY_EXISTS";
        public const string PARKING_LOT_NOT_FOUND = "PARKING_LOT_NOT_FOUND";
    }
}